m51: Set DUMMY_SHARED_LIB to camera binaries
* Fixes build errors related to copying .bin files on 15 QPR2:
error: build/soong/fsgen/Android.bp:31:1: module "lineage_m51_generated_vendor_image" variant "android_common" (created by module "soong_filesystem_creator" variant "android_common"):
 packaging conflict at lib64/camera/com.samsung.sensormodule.0_sony_imx682.bin:

Change-Id: I79ea0c6214bb462d0949b44b15020e5db3cbec5d